" Setup XDG Base Directory
set viminfofile=$XDG_STATE_HOME/vim/viminfo

" Config
imap ,, <Esc>
set clipboard+=unnamedplus
set relativenumber
set number
set tabstop=2
set shiftwidth=2
set noexpandtab
set autoindent
